language: python
sudo: true
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - mongodb

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - # Force python-dateutil version because flask-apscheduler requires this version !
  - pip install python-dateutil==2.4.2
  - ./test/setup_test.sh
# command to run tests
script:
  - cd test
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.
  - cd ..
  # Code static analysis
  - pycodestyle --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402,E722' alignak_backend/*
  - rm -fr alignak_backend/__pycache__
  # not run on python 3.6 because wait python astroid released in 1.5.0
  - if [[ $TRAVIS_PYTHON_VERSION != '3.6' ]]; then pylint --rcfile=.pylintrc alignak_backend/*; fi
  - pep257 --select=D300 alignak_backend
  # Code dynamic analysis
  - cd test
  # Delete previously existing coverage results
  - coverage erase
  # Run test suite with py.test running its coverage plugin
  - pytest --cov=alignak_backend --cov-config .coveragerc test_*.py
  # Report about coverage
  - coverage report -m
  # Test code static analysis
  - pycodestyle --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' test_*.py
  - pylint --rcfile=../.pylintrc test_*.py
  - cd ..
after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  - mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v
  - .package/package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION

deploy:
  - provider: bintray
    skip_cleanup: true
    file: .package/bintray.json
    user: ddurieux
    key:
      secure: "tFw77KIzcIRgUgJkLC5EQp/UUW+AHjqzU3Zhx5JEjAkeGyM+rhVUY6KQEzD0dgb9TaH6qmiuOicOZyhq+4gzjuIlhTeZLRarRGJrGML5n6zlx+0B6rOfcmKtMHxS+cjgz1EWKgB3n+vpmJefvKgWxfx/I8EEmDcoPGgoX2MQYSouz+NIw/eOR1BilouJ0MYuSUde8Z1rjOyhxx+Z9XtUceyiij7/DqwdwSK11vv6Ib0mEArF8joS+nOGTvRS6pXZaNGUoDKPwm2HuCvu11+KV3/gEjhxILNS5g0W11qLebPBoX2yimUy/YLrIIfpTK0QRS33Qn3dZTwHTsXPa5VX69uqYrVv+GnRgL+5sZBAbbumRu2NXH90PVqp8f7TESQGGkWqXfuy11QMCu60CDOFSSdQrJg3dyozizb5ikk9TvrzcvbeesjYTA7akFE+dM43RxvR6pFRTUwLSMnBduV/tbhH1Slu3ScZR8OHMl/ep7sS1xnfJXP8JJUO5iHbwh40Yizwg6a7BPKgDC7xoCzmUGw4umEoi1WBsbLnoJcqvm3VU0fwrYLtxaJarpt1eH8Ak5SWkfRBe8E7YV4pr7grkyBrMq1wcB1Fnv7IBibV6JTLq8HWG1441TQR+1IInJUQcl8ffpvruybvlalf/6bv8b7kKxCIe4lokWzFbEt8hrA="
    on:
      branch: develop
  - provider: bintray
    skip_cleanup: true
    file: .package/bintray.json
    user: ddurieux
    key:
      secure: "tFw77KIzcIRgUgJkLC5EQp/UUW+AHjqzU3Zhx5JEjAkeGyM+rhVUY6KQEzD0dgb9TaH6qmiuOicOZyhq+4gzjuIlhTeZLRarRGJrGML5n6zlx+0B6rOfcmKtMHxS+cjgz1EWKgB3n+vpmJefvKgWxfx/I8EEmDcoPGgoX2MQYSouz+NIw/eOR1BilouJ0MYuSUde8Z1rjOyhxx+Z9XtUceyiij7/DqwdwSK11vv6Ib0mEArF8joS+nOGTvRS6pXZaNGUoDKPwm2HuCvu11+KV3/gEjhxILNS5g0W11qLebPBoX2yimUy/YLrIIfpTK0QRS33Qn3dZTwHTsXPa5VX69uqYrVv+GnRgL+5sZBAbbumRu2NXH90PVqp8f7TESQGGkWqXfuy11QMCu60CDOFSSdQrJg3dyozizb5ikk9TvrzcvbeesjYTA7akFE+dM43RxvR6pFRTUwLSMnBduV/tbhH1Slu3ScZR8OHMl/ep7sS1xnfJXP8JJUO5iHbwh40Yizwg6a7BPKgDC7xoCzmUGw4umEoi1WBsbLnoJcqvm3VU0fwrYLtxaJarpt1eH8Ak5SWkfRBe8E7YV4pr7grkyBrMq1wcB1Fnv7IBibV6JTLq8HWG1441TQR+1IInJUQcl8ffpvruybvlalf/6bv8b7kKxCIe4lokWzFbEt8hrA="
    on:
      tags: true
