language: python
sudo: true
python:
  - "2.7"
#  - "3.4"

services:
  - mongodb

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - # Force python-dateutil version because flask-apscheduler requires this version !
  - pip install python-dateutil==2.4.2
  - ./test/setup_test.sh
# command to run tests
script:
  - cd test
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.
  - cd ..
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_backend/*
  - pylint --rcfile=.pylintrc alignak_backend/*
  - pep257 --select=D300 alignak_backend
  - cd test
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' test_*.py
  - pylint --rcfile=../.pylintrc test_*.py
  - nosetests -xv --nologcapture --process-restartworker --processes=1 --process-timeout=300
  - cd ..
