language: python
sudo: true
python:
  - "2.7"
#  - "3.4"

services:
  - mongodb

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - ./test/setup_test.sh
# command to run tests
# notice: the nose-cov is used because it is compatible with --processes, but produce a .coverage by process
# so we must combine them in the end
script:
  - cd test
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.
  - nosetests -xv --process-restartworker --processes=1 --process-timeout=300
#  - coverage combine
  - cd ..
  - pep8 --max-line-length=100 --exclude='*.pyc' alignak_backend/*
  - pylint --rcfile=.pylintrc -r no alignak_backend/*
  - pep257 --select=D300 alignak_backend
# specific call to launch coverage data into coveralls.io
#after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
#  mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v


