language: python
sudo: true
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - mongodb

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - # Force python-dateutil version because flask-apscheduler requires this version !
  - pip install python-dateutil==2.4.2
  - ./test/setup_test.sh
# command to run tests
script:
  - cd test
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.
  - cd ..
  # Code static analysis
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_backend/*
  - rm -fr alignak_backend/__pycache__
  # not run on python 3.6 because wait python astroid released in 1.5.0
  - if [[ $TRAVIS_PYTHON_VERSION != '3.6' ]]; then pylint --rcfile=.pylintrc alignak_backend/*; fi
  - pep257 --select=D300 alignak_backend
  # Code dynamic analysis
  - cd test
  # Delete previously existing coverage results
  - coverage erase
  # Run test suite with py.test running its coverage plugin
  - pytest --cov=alignak_backend --cov-config .coveragerc test_*.py
  # Report about coverage
  - coverage report -m
  # Test code static analysis
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' test_*.py
  - pylint --rcfile=../.pylintrc test_*.py
  - cd ..
after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v
